### PR TITLE
Add test for static linking of libgmp

### PR DESCRIPTION
**Pull request by olorin**
/cc @charleso @markhibberd

### CODE REVIEW

**Comment by charleso** [comment]
A :ocean: (meant to be shallow) :+1:.

As discussed IRL I personally might have been tempted to run with the normal script cli stuff and propose the alternative in disorder just to isolate that conversation, but I don't have a strong opinion about it.

**Comment by olorin** [comment]
I'm working on a PR for disorder with some utility functions for CLI tests; I can rewrite this one in shell if people want, but it'd be a lot messier.

**Comment by charleso** [comment]
Assuming you're happy with the `ldd` check I don't mind this going ahead. A separate disorder issue/pr to raise the ongoing question of `turtle` works for me too.

**Comment by olorin** [comment]
I'm happy with the `ldd` check; it fails on a dynamically-linked executable and succeeds when built with static libgmp, so probably good to go.

**Comment by markhibberd** [comment]
:+1:

**Pull request merged**
