### PR TITLE
Upgrade mismi with amazonka 1.3.2.1

### PR DESCRIPTION
**Pull request by charleso**
/cc @nhibberd This was quite a big upgrade

### CODE REVIEW

**Comment by nhibberd** [comment]
All maps to was there originally from my pov :chicken:

**Comment by markhibberd** [comment]
Think this needs an off aws test before merging.

**Comment by nhibberd** [comment]
Locally with no creds set sufficient?

**Comment by markhibberd** [comment]
@nhibberd At a minimum for now. Ideally could have a self-contained build that we could run up on a laptop.

**Comment by charleso** [comment]
@olorin tested it on his machine

**Comment by markhibberd** [comment]
@nhibberd Is this effected by multi-part issue you just hit?

**Comment by nhibberd** [comment]
The code its replace is the same version as what we currently have, possible has been an issue all along

**Pull request merged**
